name: brew pr-pull
on:
  pull_request_target:
    types:
      - labeled
env:
  HOMEBREW_NO_INSTALL_FROM_API: "1"
permissions:
  actions: read
  contents: write
  pull-requests: write
jobs:
  pr-pull:
    if: contains(github.event.pull_request.labels.*.name, 'pr-pull')
    runs-on: ubuntu-22.04
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Set up git
        uses: Homebrew/actions/git-user-config@master

      - name: Checkout PR branch
        working-directory: ${{ steps.set-up-homebrew.outputs.repository-path }}
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh pr checkout '${{ github.event.pull_request.number }}'

      - name: Pull bottles
        working-directory: ${{ steps.set-up-homebrew.outputs.repository-path }}
        env:
          HOMEBREW_GITHUB_API_TOKEN: ${{ github.token }}
          HOMEBREW_GITHUB_PACKAGES_TOKEN: ${{ github.token }}
          HOMEBREW_GITHUB_PACKAGES_USER: ${{ github.actor }}
        run: |
          brew pr-pull \
            --debug \
            --clean \
            --no-cherry-pick \
            --tap='${{ github.repository }}' \
            --workflows=tests.yml \
            '${{ github.event.pull_request.number }}'

      - name: Push commits
        uses: Homebrew/actions/git-try-push@master
        with:
          token: ${{ github.token }}
          directory: ${{ steps.set-up-homebrew.outputs.repository-path }}
          branch: ${{ github.head_ref }}

      - name: Merge PR
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh pr merge --delete-branch --merge '${{ github.event.pull_request.number }}'
