name: brew pr-pull

on:
  pull_request_target:
    types:
      - labeled

permissions:
  actions: read
  contents: write
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: false

env:
  HOMEBREW_NO_INSTALL_FROM_API: "1"

jobs:
  pr-pull:
    if: contains(github.event.pull_request.labels.*.name, 'pr-pull')
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/homebrew/ubuntu22.04:master
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Set up git
        uses: Homebrew/actions/git-user-config@master

      - name: Checkout PR branch
        working-directory: ${{ steps.set-up-homebrew.outputs.repository-path }}
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh pr checkout '${{ github.event.pull_request.number }}'

      - name: Pull bottles
        working-directory: ${{ steps.set-up-homebrew.outputs.repository-path }}
        env:
          HOMEBREW_GITHUB_API_TOKEN: ${{ github.token }}
        run: |
          brew pr-pull \
            --debug \
            --clean \
            --no-cherry-pick \
            --tap='${{ github.repository }}' \
            --workflows=tests.yml \
            '${{ github.event.pull_request.number }}'

      - name: Push commits
        uses: Homebrew/actions/git-try-push@master
        with:
          token: ${{ github.token }}
          directory: ${{ steps.set-up-homebrew.outputs.repository-path }}
          branch: ${{ github.head_ref }}

      - name: Remove `pr-pull` label on failure
        if: failure()
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh pr edit \
            --remove-label=pr-pull \
            '${{ github.event.pull_request.number }}'

      - name: Merge PR
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh pr merge \
            --delete-branch \
            --merge \
            '${{ github.event.pull_request.number }}'
